name: Build and Push Docker Image

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: mip92/tattoo-server

jobs:
  test-access:
    runs-on: ubuntu-latest

    steps:
      - name: Test access to tattoo repository
        uses: actions/checkout@v4
        with:
          repository: mip92/tattoo
          token: ${{ secrets.PAT_TOKEN }}
          path: tattoo

      - name: Show repository info
        run: |
          cd tattoo
          echo "Repository accessed successfully!"
          echo "Current branch: $(git branch --show-current)"
          echo "Last commit: $(git log -1 --oneline)"

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Success message
        run: echo "Docker image successfully built and pushed to Docker Hub!"

  deploy-to-nginx:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout tattoo repository
        uses: actions/checkout@v4
        with:
          repository: mip92/tattoo
          token: ${{ secrets.PAT_TOKEN }}
          path: tattoo

      - name: Check for changes
        id: check-changes
        run: |
          cd tattoo
          if git diff --quiet HEAD~1 HEAD; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "No changes detected, skipping deployment"
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
            echo "Changes detected, proceeding with deployment"
          fi

      - name: Debug repository dispatch
        if: steps.check-changes.outputs.no_changes == 'false'
        run: |
          echo "🔍 Debug info:"
          echo "Repository: mip92/tattoo"
          echo "Event type: deploy-backend"
          echo "Token exists: ${{ secrets.PAT_TOKEN != '' }}"
          echo "Token length: ${#PAT_TOKEN}"

      - name: Trigger deployment action
        if: steps.check-changes.outputs.no_changes == 'false'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: mip92/tattoo
          event-type: deploy-backend
          client-payload: '{"backend_image": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"}'

      - name: Confirm dispatch sent
        if: steps.check-changes.outputs.no_changes == 'false'
        run: |
          echo "✅ Repository dispatch event sent to mip92/tattoo"
          echo "Event type: deploy-backend"
          echo "Backend image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
